/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

//import com.sun.corba.se.pept.transport.Connection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import app.MyConnection;
import java.awt.event.KeyEvent;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Chathura dinushka
 */
public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form carmanagement
     */
    public Driver() {
        initComponents();
        DisplayDrivers();
        setLocationRelativeTo(null);
        displayid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_drivers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_driTele = new javax.swing.JTextField();
        txt_driNIC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox<>();
        btn_reset = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_driverID = new javax.swing.JTextField();
        txt_driverName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setText("   Drivers Detals Management");

        table_drivers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "DriverID", "Name", "Status", "TelephoneNo", "NIC"
            }
        ));
        table_drivers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_driversMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_drivers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NIC");

        txt_driTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_driTeleActionPerformed(evt);
            }
        });
        txt_driTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_driTeleKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        cmb_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Booked", "Available" }));
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(153, 153, 153));
        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setText("Clear");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(153, 153, 153));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(153, 153, 153));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Telephone No");

        btn_edit.setBackground(new java.awt.Color(153, 153, 153));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Driver ID");

        txt_driverName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_driverNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_driverNameKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Driver Name");

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_status, 0, 214, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_driverName, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(txt_driverID)
                        .addComponent(txt_driTele)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_driNIC))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_driverID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_driverName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_driTele, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(txt_driNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset)
                    .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    MyConnection conManager = new MyConnection();
    
    Connection con = null;
    Statement st = null;
    ResultSet rs =  null;
    
        private void displayid(){
        
        try{
        con = conManager.createConnection();
        st=con.createStatement();
        
        rs=st.executeQuery("SELECT MAX(DriverID) from drivers");
        rs.next();
        
        rs.getString("MAX(DriverID)");
        
        if( rs.getString("MAX(DriverID)")==null){
            
            txt_driverID.setText("DID1");
        
            }
       
        else{
                Long id=Long.parseLong(rs.getString("MAX(DriverID)").substring(3,rs.getString("MAX(DriverID)").length())); 
                id++;
                txt_driverID.setText("DID"+String.format("%d",id));
                
            }
        
        txt_driverID.setEditable(false);
        }
        
        catch (SQLException e)
        {
            e.printStackTrace();
         
        }
    }
    
    // Display full details of drivers
     private void DisplayDrivers()
     {
         try{
            // Make connection 
            
            con = conManager.createConnection();
           
            String sql = "SELECT * FROM drivers";
            PreparedStatement pstmt = con.prepareStatement(sql);
            rs = pstmt.executeQuery();
            
            // Set to table
            table_drivers.setModel(DbUtils.resultSetToTableModel(rs));
         
         } 
         catch (SQLException e)
         {
            e.printStackTrace();
         
         }
     } 

     // Save driver details
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (txt_driverID.getText().isEmpty()|| txt_driverName.getText().isEmpty() || txt_driTele.getText().isEmpty() || txt_driNIC.getText().isEmpty() || cmb_status.getSelectedIndex() == 0 )
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        {
            try 
            {
                Session s = connection.Controller.getSessionFactory().openSession();
                Transaction tr = s.beginTransaction();

                pojos.Drivers driver = new pojos.Drivers();
                driver.setDriverId(txt_driverID.getText());
                driver.setName(txt_driverName.getText());
                driver.setStatus(cmb_status.getSelectedItem().toString());
                driver.setTelephoneNo(Integer.valueOf(txt_driTele.getText()));
                driver.setNic(txt_driNIC.getText());

                s.save(driver);
                tr.commit();


                s.close();
                tr = null;
                JOptionPane.showMessageDialog(this,"Driver details Added successfuly");

                DisplayDrivers();
                Reset();

            }
            catch (Exception e){
               e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    // Delete driver details
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
       
        if (txt_driverID.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(this,"Select the Driver to be Deleted");
        }
        else
        {
            try 
            {
                con = conManager.createConnection();
                
                String DID = txt_driverID.getText();
                String Query = "Delete from car_rental_system.drivers where DriverID = '"+ DID +"'" ;
                Statement Add =  con.createStatement();
                Add.executeUpdate(Query);
                JOptionPane.showMessageDialog(this,"Driver details Deleted successfuly");

                DisplayDrivers();
                Reset();


            }
            catch (Exception e)
            {
               e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed
    // To clear all textbox
    private void Reset()
    {
       txt_driverID.setText("");
        txt_driverName.setText("");
        txt_driTele.setText("");
        cmb_status.setSelectedIndex(0);
        txt_driNIC.setText("");
    }
    
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        Reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_driTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_driTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_driTeleActionPerformed

    // Edit driver details
    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (txt_driverID.getText().isEmpty() || txt_driverName.getText().isEmpty() || txt_driTele.getText().isEmpty() || txt_driNIC.getText().isEmpty() || cmb_status.getSelectedIndex() == 0 )
        {
            JOptionPane.showMessageDialog(this,"Select the Driver to be Updated");
        }
        else
        {
            try 
            {
                con = conManager.createConnection();
                
                String DID = txt_driverID.getText();
                String Query = "Update  car_rental_system.drivers set Name= '"+txt_driverName.getText()+ "', Status='"+cmb_status.getSelectedItem().toString()+"', TelephoneNo='"+txt_driTele.getText()+"', NIC = '"+txt_driNIC.getText()+"' where DriverID ='"+DID+"'" ;
                Statement Add =  con.createStatement();
                Add.executeUpdate(Query);
                JOptionPane.showMessageDialog(this,"Driver details Updated successfuly");


                DisplayDrivers();
                Reset();


            }catch (Exception e){
               e.printStackTrace();
            }
        } 
    }//GEN-LAST:event_btn_editActionPerformed

    private void table_driversMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_driversMouseClicked
        DefaultTableModel model = (DefaultTableModel)table_drivers.getModel();
        int MyIndex = table_drivers.getSelectedRow();
        txt_driverID.setText(model.getValueAt(MyIndex, 0).toString());
        txt_driverName.setText(model.getValueAt(MyIndex, 1).toString());
        txt_driTele.setText(model.getValueAt(MyIndex, 3).toString());
        cmb_status.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
        txt_driNIC.setText(model.getValueAt(MyIndex, 4).toString());
        
        
    }//GEN-LAST:event_table_driversMouseClicked

    private void txt_driTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_driTeleKeyPressed
        // TODO add your handling code here:
        //Phone number validation
        String number=txt_driTele.getText();
        int num=number.length();
        
        char c=evt.getKeyChar();
        //check for number 0 to 9 and length<=10
        if(c>='0' && c<='9'){
            if(num<10){
               txt_driTele.setEditable(true);
            }
            else{
                txt_driTele.setEditable(false);
               
                
            }
        
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                
                txt_driTele.setEditable(true);
            
            }
            else{
                txt_driTele.setEditable(false);  
                JOptionPane.showMessageDialog(this,"Enter only numbers");
            }
        
        }
    }//GEN-LAST:event_txt_driTeleKeyPressed

    private void txt_driverNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_driverNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_driverNameKeyReleased

    private void txt_driverNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_driverNameKeyPressed
        // TODO add your handling code here:
        //name field validation
        char c=evt.getKeyChar();
        
        if(Character.isLetter(c)|| Character.isWhitespace(c) || Character.isISOControl(c)){

            txt_driverName.setEditable(true);
            
        }
        else{
        
            txt_driverName.setEditable(false);
            JOptionPane.showMessageDialog(this,"Enter only letters");
        }
    }//GEN-LAST:event_txt_driverNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_drivers;
    private javax.swing.JTextField txt_driNIC;
    private javax.swing.JTextField txt_driTele;
    private javax.swing.JTextField txt_driverID;
    private javax.swing.JTextField txt_driverName;
    // End of variables declaration//GEN-END:variables
}
