package pojos;
// Generated Aug 7, 2022 12:31:41 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String adminId;
     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String adminId, String username, String password) {
       this.adminId = adminId;
       this.username = username;
       this.password = password;
    }
   
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


