package pojos;
// Generated Aug 7, 2022 12:31:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private String carId;
     private String brand;
     private String model;
     private String status;
     private int price;
     private Set rents = new HashSet(0);

    public Cars() {
    }

	
    public Cars(String carId, String brand, String model, String status, int price) {
        this.carId = carId;
        this.brand = brand;
        this.model = model;
        this.status = status;
        this.price = price;
    }
    public Cars(String carId, String brand, String model, String status, int price, Set rents) {
       this.carId = carId;
       this.brand = brand;
       this.model = model;
       this.status = status;
       this.price = price;
       this.rents = rents;
    }
   
    public String getCarId() {
        return this.carId;
    }
    
    public void setCarId(String carId) {
        this.carId = carId;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Set getRents() {
        return this.rents;
    }
    
    public void setRents(Set rents) {
        this.rents = rents;
    }




}


