package pojos;
// Generated Aug 7, 2022 12:31:41 PM by Hibernate Tools 4.3.1



/**
 * Customerdata generated by hbm2java
 */
public class Customerdata  implements java.io.Serializable {


     private String customerId;
     private String name;
     private String address;
     private int telephoneNo;

    public Customerdata() {
    }

    public Customerdata(String customerId, String name, String address, int telephoneNo) {
       this.customerId = customerId;
       this.name = name;
       this.address = address;
       this.telephoneNo = telephoneNo;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getTelephoneNo() {
        return this.telephoneNo;
    }
    
    public void setTelephoneNo(int telephoneNo) {
        this.telephoneNo = telephoneNo;
    }




}


