package pojos;
// Generated Aug 7, 2022 12:31:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Returns generated by hbm2java
 */
public class Returns  implements java.io.Serializable {


     private String returnId;
     private Rent rent;
     private Date carReturnDate;
     private int delayDates;
     private int delayAmount;

    public Returns() {
    }

    public Returns(String returnId, Rent rent, Date carReturnDate, int delayDates, int delayAmount) {
       this.returnId = returnId;
       this.rent = rent;
       this.carReturnDate = carReturnDate;
       this.delayDates = delayDates;
       this.delayAmount = delayAmount;
    }
   
    public String getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(String returnId) {
        this.returnId = returnId;
    }
    public Rent getRent() {
        return this.rent;
    }
    
    public void setRent(Rent rent) {
        this.rent = rent;
    }
    public Date getCarReturnDate() {
        return this.carReturnDate;
    }
    
    public void setCarReturnDate(Date carReturnDate) {
        this.carReturnDate = carReturnDate;
    }
    public int getDelayDates() {
        return this.delayDates;
    }
    
    public void setDelayDates(int delayDates) {
        this.delayDates = delayDates;
    }
    public int getDelayAmount() {
        return this.delayAmount;
    }
    
    public void setDelayAmount(int delayAmount) {
        this.delayAmount = delayAmount;
    }




}


